### PR TITLE
Rahull

### PR DESCRIPTION
**Pull request by rahull1706**

### CODE REVIEW

**Comment by Sameer0410** [comment]
Ok rahul

**Comment by Sameer0410** [comment]
https://github.com/sheetalkader1/hackathondbs

**Comment by Sameer0410** [comment]
It has all the answers broo just check it once

**Comment by Sameer0410** [comment]
bro did you receive a call regarding interview

**Comment by rahull1706** [comment]
Yeah bro I had received call
Did you know about all the other people in our grp

**Comment by Sameer0410** [comment]
Ok...ok...all the best bro

**Pull request merged**
